config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users
  get '/home/about', to: 'homes#about', as: 'about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites,dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


validates :title, presence: true
validates :body, length: { maximum: 200 },presence: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # has_many :favorites,dependent: :destroy
  # コメントアウト理由はfavoriteのmodel参照

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # belongs_to :book_comment
  # コメント機能にもいいね付けたくアソシエーションしたが、いいねする際に「コメントが空白のためエラー」が発生し、いいねがsaveされなかったためコメントアウト
  # 上のエラーちょっと意味が違うかも、favoritesテーブルのbook_comment_idがブランクになってしまうから保存できないという意味か？
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,except: [:top,:about]

def after_sign_in_path_for(resource)
   user_path(current_user.id)
end


before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)

  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @books = Book.all

     #@users = Book.find(user_id)
  end

  def create
   @user = current_user
   @books =Book.all
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
      flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
   else
      render 'index'
   end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
    @book_comment = BookComment.new
    # @book_comments = BookComment.find(@user)
    #@user = User.find(params[:id])
    #@user = current_user
    #@bookss = @books.user
  end

  def edit
    @book = Book.find(params[:id])
     unless
    @book.user == current_user
     redirect_to books_path
     end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id:book.id)
    favorite.save!
    redirect_to request.referer
  end

  def destroy

    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end 
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @users = User.all
     #@users = Book.find(user_id)
  end
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @userbook = @user.books.page(params[:page]).reverse_order
  end
  
  def create
  end
  
  def edit
    @user = User.find(params[:id])
    unless 
    @user. == current_user
     redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) 
    else
      render 'edit'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        
        <% if @book.errors.any? %>
        <div class="error_explanation">
          <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
        <% end %>
                
            <%= form_with model:@book, local:true do |f| %>
            <div class="form-group">
              <label for="inputName">Title</label>
              <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:"名前"%>
            </div>
            <div class="form-group">
              <label for="introduction">Opinion</label>
              <%= f.text_field :body, autofocus: true, id:"introduction", placeholder:"自己紹介文"%>
            </div>
              <%= f.submit "Update Book" ,class:'btn btn-success'%>
            <% end %>

              <%=(link_to"Show", book_path(params[:id]) ,{class: "book"})%>
            |
              <%=(link_to"Back", books_path, {class: "book"})%>
    </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
  <div class="error_explanation">
    <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>


   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th colspan="0"></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="0"></th>
        </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(book.user) do %>
           <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>

        <td>
         <% if book.favorited_by?(current_user) %>
          <p><%= link_to book_favorites_path(book.id), method: :delete do %>
              ♥<%= book.favorites.count %> いいね
            <% end %>
          </p>

          <% else %>
          <p><%= link_to book_favorites_path(book.id), method: :post do %>
              ♡<%= book.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
        </td>

        <td>コメント数： <%= book.book_comments.count %></td>

        <% end %>
       </tr>

    </tbody>
    </table>
    </div>
  </div>
</div>
</main>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
    <tbody class ="BookShow">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(params[:id]) do %>
            <%= @books.title %>
            <% end %>
            </td>
          <td>
            <%= @books.body %>
          </td>

          <td>
            <% if @books.user == current_user %>
            <div class=row>
              <%= link_to "Edit", edit_book_path(params[:id]),class:'btn btn-sm btn-success edit_book_765' %>
            </div>
            <% end %>
          </td>

          <td>
            <% if @books.user == current_user %>
              <div class=row>
                <%= link_to "Destroy", book_path(params[:id]),class:'btn btn-sm btn-danger destroy_book_765', method: :delete ,data: { confirm: '本当に消しますか？' } %>
              </div>
            <% end %>
          </td>
          
          <td>
             <% if @books.favorited_by?(current_user) %>
              <p><%= link_to book_favorites_path(@books.id), method: :delete do %>
                  ♥<%= @books.favorites.count %> いいね
                <% end %>
              </p>
      
              <% else %>
              <p><%= link_to book_favorites_path(@books.id), method: :post do %>
                  ♡<%= @books.favorites.count %> いいね
                <% end %>
              </p>
            <% end %>
          </td>
          
          <td>
            コメント件数：<%= @books.book_comments.count %>
          </td>
          
        </tr>
    </tbody>
    </table>

    <div class="comments">
 
     <table>
       <thead>
         <tr>
         </tr>
       </thead>
       <tbody>
            <% @books.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
                <%= book_comment.user.name %>
                <% end %>
              </td>

              <!--<td><%#= book_comment.created_at.strftime('%Y/%m/%d') %></td>-->
              <td><%= book_comment.comment %></td>

              <% if book_comment.user == current_user %>
              <td>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment),class:'btn btn-sm btn-danger destroy_book_765',method: :delete %>
              </td>
              <% end %>

            <% end %>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="new-comment">
      <%= form_with(model:[@books, @book_comment], local: true) do |f| %>
      <p><%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %></p>
      <p><%= f.submit "送信する" %></p>
      <% end %>
    </div>



</div>
</div>
</div>



<div clss="comment">
  <table>
    <thead>

    </thead>

    <tbody>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </tbody>

  </table>

</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">

      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i><strong>Bookers</strong>
          !!
        </h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to("Log in", new_user_session_path,{class: "btn btn-info btn-sm btn-block mb-3 sign_in"}) %>
          </div>
          <div class="row">
            <%= link_to("Sign Up", new_user_registration_path,{class: "btn btn-success btn-sm btn-block sign_up"}) %>
          </div>
      </div>
    </div>
   </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">

       <a href="/">
         <span class="navbar-brand">Bookers</span>
       </a>

       <!--要件にaタグで書くよう指示があったためコメントアウトし上記aタグ作成-->
       <%# link_to("Bookers","/",  {class: "navbar-brand"}) %>
       <!--課題3合格済-->

       <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
     <li>
        <%= link_to("Home", user_path(current_user.id),{class: "fas fa-home nav-link text-light"}) %>
      </li>
     <li>
        <%= link_to("Users", users_path, {class: "fas fa-users nav-link text-light"}) %>
      </li>
     <li>
        <%= link_to("Books", '/books',{class: "fas fa-book-open nav-link text-light"}) %>
      </li>
      <li>
        <%= link_to("logout", destroy_user_session_path, {method: :delete,class: "fas fa-sign-out-alt nav-link text-light"}) %>
      </li>
    <% else %>
      <li>
      <%= link_to("Home", "/",{class: "fas fa-home nav-link text-light"} )%>
      </li>
      <li>
        <%= link_to("About", about_path,{class: "fas fa-link nav-link text-light"} )%>
      </li>
      <li>
     <%= link_to("sign up", new_user_registration_path,{class: "fas fa-user-plus nav-link text-light"} )%>
      </li>
      <li>
        <%= link_to("login", new_user_session_path,{class: "fas fa-sign-in-alt nav-link text-light"} )%>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
        </nav>
    </header>

    <main>
    <% flash.each do |message_type, message|%>
    <%= content_tag :div, message, class: message_type %>
    <% end %>
    <p id="notice"></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_sidebar.html.erb
<!--ログイン後のほぼ共通パーツ　ここから-->
 <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
       <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
  </tbody>
  </table>
  
   
    <dev class=row><%= link_to("", edit_user_path(user),{class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_266"}) %></dev>
  
  
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label>Title </label>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label>Opinion </label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        
      
        <% if @user.errors.any? %>
         <div class="error_explanation">
          <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
           <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
         </div>
        <% end %>
      
        
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
          </div>
          
          <div class="form-group">
            <label for="inputImage">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          
          <div class="form-group">
            <label for="introduction">introduction</label>
            <%= f.text_field :introduction, autofocus: true, id:"introduction", placeholder:"自己紹介文"%>
          </div>
          
          <div class="form-group">
            <%= f.submit "Update User" ,:class => 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>


   <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th>image</th>
          <th>Name</th>
          <th colspan="0"></th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= link_to "Show", user_path(user.id)  %>
          </td>
        </tr>

    <% end %>
    </tbody>
    </table>
    </dev>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>
   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th colspan="0"></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
    </thead>
     <tbody>
    <% @userbook.each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(@user) do %>
           <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>
          <td>コメント件数：<%= book.book_comments.count %></td>
        </tr>
    <% end %>
    </table>
     </tbody>
    </div>
   </div>
  </div>